mod adapter;
pub(crate) mod app_inventory;
pub(crate) mod app_ops;
pub(crate) mod appkit_bridge;
pub(crate) mod cg_window;
pub(crate) mod cg_window_exact;
pub(crate) mod cocoa_runtime;
pub(crate) mod cursor_overlay;
pub(crate) mod display;
pub(crate) mod display_work_area;
pub(crate) mod focus;
pub(crate) mod key_dispatch;
pub(crate) mod launch;
pub(crate) mod launch_callback_result;
pub(crate) mod launch_completion;
pub(crate) mod launch_workspace;
pub(crate) mod permission_helper;
pub(crate) mod permission_operation;
pub(crate) mod permissions;
pub(crate) mod process;
pub(crate) mod process_apps;
pub(crate) mod process_identity;
pub(crate) mod process_state;
pub(crate) mod renderer_activation;
pub(crate) mod renderer_kind;
pub(crate) mod screenshot;
pub(crate) mod signals;
pub(crate) mod wait;
pub(crate) mod window_ax_state;
pub(crate) mod window_bridge;
pub(crate) mod window_inventory;
pub(crate) mod window_inventory_global;
pub(crate) mod window_ops;
pub(crate) mod window_postcondition;
pub(crate) mod window_resolve;
pub(crate) mod workspace_apps;

#[cfg(test)]
#[path = "screen_bridge_contract_tests.rs"]
mod screen_bridge_contract_tests;
