#!/usr/bin/env bash
#
# Enforces the two source-shape rules no compiler checks: the per-file line cap
# and the ban on non-doc comments.
#
# Both halves are only a gate if they can run, and if they still fire once they
# do. This script therefore probes for an interpreter instead of hardcoding one
# - `python3` does not exist on a Windows developer box, and hardcoding it made
# the comment half exit without checking anything while violations reached CI -
# and it runs a self-test over its own cap rule before scanning the tree, so a
# rule that has stopped detecting anything fails the gate rather than passing it
# in silence.

set -euo pipefail

cd "$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

limit=400

# The single owner of the cap rule. The tree scan and `self_test` both call it,
# so the fixture exercises the shipped rule instead of a copy that can drift
# away from it.
#
# Counting and the `@generated` exemption share one awk pass, for two reasons.
# `wc -l` counts newlines rather than lines, so a file whose final line is
# unterminated read one short and a 401-line file without a trailing newline
# slipped the cap; awk counts records, and an unterminated final line is a
# record. And reading the marker through `head | grep` hangs the verdict on a
# pipeline whose exit status depends on which side finishes first. A generated
# file reports -1, which no limit can exceed.
oversize_report() {
    local file="$1"
    local lines
    lines="$(
        awk '
            NR <= 5 && index($0, "@generated") { generated = 1 }
            END { print (generated ? -1 : NR) }
        ' "$file"
    )"
    if [ "$lines" -gt "$limit" ]; then
        printf '%s: %s lines (limit %s)\n' "$file" "$lines" "$limit"
        return 1
    fi
    return 0
}

resolve_interpreter() {
    local candidate
    for candidate in python3 python py; do
        if command -v "$candidate" >/dev/null 2>&1 &&
            "$candidate" -c 'import sys; raise SystemExit(0 if sys.version_info[0] >= 3 else 1)' \
                >/dev/null 2>&1; then
            printf '%s\n' "$candidate"
            return 0
        fi
    done
    return 1
}

# Finding nothing is a failure, never a skip: a comment rule that quietly stops
# running is indistinguishable from a clean tree.
require_interpreter() {
    local found
    if ! found="$(resolve_interpreter)"; then
        printf 'no working Python 3 interpreter on PATH (tried python3, python, py)\n' >&2
        return 1
    fi
    printf '%s\n' "$found"
}

SELF_TEST_DIR=""

cleanup_self_test() {
    if [ -n "$SELF_TEST_DIR" ]; then
        rm -rf "$SELF_TEST_DIR"
        SELF_TEST_DIR=""
    fi
}

# Both directions are driven, because a rule that rejects everything is as
# useless as one that rejects nothing, and only one of the two announces itself.
self_test() {
    local failures under over unterminated generated empty_path
    failures=0
    SELF_TEST_DIR="$(mktemp -d)"
    trap cleanup_self_test EXIT

    under="$SELF_TEST_DIR/under.rs"
    over="$SELF_TEST_DIR/over.rs"
    unterminated="$SELF_TEST_DIR/unterminated.rs"
    generated="$SELF_TEST_DIR/generated.rs"

    awk -v limit="$limit" 'BEGIN { for (i = 1; i <= limit; i++) print "fn line() {}" }' >"$under"
    awk -v limit="$limit" 'BEGIN { for (i = 1; i <= limit + 1; i++) print "fn line() {}" }' >"$over"
    awk -v limit="$limit" '
        BEGIN {
            for (i = 1; i <= limit; i++) print "fn line() {}"
            printf "fn unterminated_last_line() {}"
        }
    ' >"$unterminated"
    {
        printf '// @generated by a tool\n'
        awk -v limit="$limit" 'BEGIN { for (i = 1; i <= limit + 1; i++) print "fn line() {}" }'
    } >"$generated"

    if oversize_report "$over" >/dev/null 2>&1; then
        printf 'self-test FAIL (missed): a %s-line file did not trip the %s-line cap\n' \
            "$((limit + 1))" "$limit" >&2
        failures=1
    fi
    if oversize_report "$unterminated" >/dev/null 2>&1; then
        printf 'self-test FAIL (missed): a %s-line file with no trailing newline did not trip the cap\n' \
            "$((limit + 1))" >&2
        failures=1
    fi
    if ! oversize_report "$under" >/dev/null 2>&1; then
        printf 'self-test FAIL (false positive): a %s-line file tripped the %s-line cap\n' \
            "$limit" "$limit" >&2
        failures=1
    fi
    if ! oversize_report "$generated" >/dev/null 2>&1; then
        printf 'self-test FAIL (false positive): an @generated file tripped the cap it is exempt from\n' >&2
        failures=1
    fi

    # A machine with no interpreter must fail the gate, never skip it quietly:
    # that silent skip is how 27 comment violations across 7 files reached CI.
    # The probe runs against a search path holding nothing at all, with the
    # command hash cleared so a previously resolved path cannot answer for it.
    empty_path="$SELF_TEST_DIR/empty-search-path"
    mkdir -p "$empty_path"
    if (
        export PATH="$empty_path"
        hash -r 2>/dev/null || true
        require_interpreter
    ) >/dev/null 2>&1; then
        printf 'self-test FAIL: the interpreter probe reported success with an empty search path\n' >&2
        failures=1
    fi

    cleanup_self_test
    if [ "$failures" -ne 0 ]; then
        printf 'The Rust source-shape rules do not behave as documented.\n' >&2
        return 1
    fi
    return 0
}

failed=0

self_test || failed=1

while IFS= read -r file; do
    [ -f "$file" ] || continue
    oversize_report "$file" >&2 || failed=1
done < <(git ls-files --cached --others --exclude-standard -- '*.rs')

if interpreter="$(require_interpreter)"; then
    if ! git ls-files -z --cached --others --exclude-standard -- '*.rs' |
        "$interpreter" scripts/check_rust_comments.py; then
        failed=1
    fi
else
    failed=1
fi

if [ "$failed" -ne 0 ]; then
    exit 1
fi
