//! C-boundary validation for every `#[repr(i32)]` enum exposed to C.
//!
//! Public ABI structs (`AdAction`, `AdMouseEvent`, `AdWindowOp`, etc.)
//! store their enum-typed fields as raw `int32_t`. A foreign caller
//! therefore never writes into a Rust enum slot, which would otherwise
//! be undefined behavior on an out-of-range discriminant. Each raw
//! value is converted to its typed enum via `<Enum>::from_c(raw: i32)`
//! (generated by `try_from_c_enum!`); `None` → the FFI entrypoint
//! returns `AD_RESULT_ERR_INVALID_ARGS`.

use crate::types::{
    AdActionKind, AdDirection, AdImageFormat, AdModifier, AdMouseButton, AdMouseEventKind,
    AdScreenshotKind, AdSnapshotSurface, AdWindowOpKind,
};

macro_rules! try_from_c_enum {
    ($ty:ty { $($variant:ident = $val:expr),+ $(,)? }) => {
        impl $ty {
            #[allow(dead_code)] // not every enum is read from C today; keep the validator uniformly
            pub(crate) fn from_c(raw: i32) -> Option<Self> {
                match raw {
                    $($val => Some(<$ty>::$variant),)+
                    _ => None,
                }
            }
        }
    };
}

try_from_c_enum! {
    AdActionKind {
        Click = 0, DoubleClick = 1, RightClick = 2, TripleClick = 3,
        SetValue = 4, SetFocus = 5, Expand = 6, Collapse = 7,
        Select = 8, Toggle = 9, Check = 10, Uncheck = 11,
        Scroll = 12, ScrollTo = 13, PressKey = 14, KeyDown = 15,
        KeyUp = 16, TypeText = 17, Clear = 18, Hover = 19, Drag = 20,
    }
}

try_from_c_enum! {
    AdDirection {
        Up = 0, Down = 1, Left = 2, Right = 3,
    }
}

try_from_c_enum! {
    AdModifier {
        Cmd = 0, Ctrl = 1, Alt = 2, Shift = 3,
    }
}

try_from_c_enum! {
    AdMouseButton {
        Left = 0, Right = 1, Middle = 2,
    }
}

try_from_c_enum! {
    AdMouseEventKind {
        Move = 0, Down = 1, Up = 2, Click = 3,
    }
}

try_from_c_enum! {
    AdWindowOpKind {
        Resize = 0, Move = 1, Minimize = 2, Maximize = 3, Restore = 4,
    }
}

try_from_c_enum! {
    AdScreenshotKind {
        Screen = 0, Window = 1, FullScreen = 2,
    }
}

try_from_c_enum! {
    AdImageFormat {
        Png = 0, Jpg = 1,
    }
}

try_from_c_enum! {
    AdSnapshotSurface {
        Window = 0, Focused = 1, Menu = 2, Menubar = 3,
        Sheet = 4, Popover = 5, Alert = 6,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_action_kind_valid_range() {
        for raw in 0..=20 {
            assert!(AdActionKind::from_c(raw).is_some(), "raw = {}", raw);
        }
    }

    #[test]
    fn test_action_kind_out_of_range() {
        assert!(AdActionKind::from_c(-1).is_none());
        assert!(AdActionKind::from_c(21).is_none());
        assert!(AdActionKind::from_c(999).is_none());
        assert!(AdActionKind::from_c(i32::MAX).is_none());
        assert!(AdActionKind::from_c(i32::MIN).is_none());
    }

    #[test]
    fn test_direction_valid_range() {
        for raw in 0..=3 {
            assert!(AdDirection::from_c(raw).is_some());
        }
        assert!(AdDirection::from_c(4).is_none());
    }

    #[test]
    fn test_modifier_valid_range() {
        for raw in 0..=3 {
            assert!(AdModifier::from_c(raw).is_some());
        }
        assert!(AdModifier::from_c(-5).is_none());
    }

    #[test]
    fn test_mouse_button_valid_range() {
        assert!(AdMouseButton::from_c(0).is_some());
        assert!(AdMouseButton::from_c(2).is_some());
        assert!(AdMouseButton::from_c(3).is_none());
    }

    #[test]
    fn test_mouse_event_kind_valid_range() {
        assert!(AdMouseEventKind::from_c(0).is_some());
        assert!(AdMouseEventKind::from_c(3).is_some());
        assert!(AdMouseEventKind::from_c(4).is_none());
    }

    #[test]
    fn test_window_op_kind_valid_range() {
        assert!(AdWindowOpKind::from_c(0).is_some());
        assert!(AdWindowOpKind::from_c(4).is_some());
        assert!(AdWindowOpKind::from_c(5).is_none());
    }

    #[test]
    fn test_screenshot_kind_valid_range() {
        assert!(AdScreenshotKind::from_c(0).is_some());
        assert!(AdScreenshotKind::from_c(2).is_some());
        assert!(AdScreenshotKind::from_c(3).is_none());
    }

    #[test]
    fn test_image_format_valid_range() {
        assert!(AdImageFormat::from_c(0).is_some());
        assert!(AdImageFormat::from_c(1).is_some());
        assert!(AdImageFormat::from_c(2).is_none());
    }

    #[test]
    fn typed_enum_cast_round_trips_through_raw_i32() {
        let raw = AdActionKind::Scroll as i32;
        assert_eq!(raw, 12);
        let back = AdActionKind::from_c(raw).unwrap();
        assert!(matches!(back, AdActionKind::Scroll));
    }

    #[test]
    fn fuzz_arbitrary_bit_patterns_never_panic_across_all_enums() {
        for raw in [-1_000_000_i32, -1, 0, 1, 20, 21, 999, i32::MAX, i32::MIN] {
            let _ = AdActionKind::from_c(raw);
            let _ = AdDirection::from_c(raw);
            let _ = AdModifier::from_c(raw);
            let _ = AdMouseButton::from_c(raw);
            let _ = AdMouseEventKind::from_c(raw);
            let _ = AdWindowOpKind::from_c(raw);
            let _ = AdScreenshotKind::from_c(raw);
            let _ = AdImageFormat::from_c(raw);
        }
    }
}
