//! C-boundary validation for every `#[repr(i32)]` enum exposed to C.
//!
//! A C caller can write an arbitrary `int32_t` into the enum-typed field
//! of a `#[repr(C)]` struct. Reading that field as the Rust enum type
//! and pattern-matching against its variants triggers **undefined
//! behavior** when the discriminant is out-of-range — Rust is allowed
//! to assume enum values are always valid.
//!
//! The pattern in this module avoids that UB entirely:
//!
//! 1. Never read the field as the enum type. Instead, read the raw
//!    `i32` bytes via `enum_raw_i32`, which does a byte-level memcpy
//!    through a pointer cast — always defined behavior.
//! 2. Convert the raw `i32` back into the enum via `<Enum>::from_c`
//!    (generated by the `try_from_c_enum!` macro). The generated match
//!    only yields `Some(Variant)` for known-good discriminants; an
//!    unknown bit pattern returns `None` and the caller returns
//!    `AD_RESULT_ERR_INVALID_ARGS`.
//!
//! The field-type stays the enum so cbindgen keeps emitting the strongly
//! typed C signatures — the memory layout is identical to `int32_t`
//! thanks to `#[repr(i32)]`.

use crate::types::{
    AdActionKind, AdDirection, AdImageFormat, AdModifier, AdMouseButton, AdMouseEventKind,
    AdScreenshotKind, AdSnapshotSurface, AdWindowOpKind,
};

/// Reads the raw `i32` discriminant out of an `#[repr(i32)]` enum field
/// without invoking the enum's validity invariant. Safe because
/// `#[repr(i32)]` guarantees the bit layout matches `i32`.
pub(crate) fn enum_raw_i32<T>(field: &T) -> i32 {
    debug_assert_eq!(std::mem::size_of::<T>(), std::mem::size_of::<i32>());
    unsafe { std::ptr::read(field as *const T as *const i32) }
}

macro_rules! try_from_c_enum {
    ($ty:ty { $($variant:ident = $val:expr),+ $(,)? }) => {
        impl $ty {
            #[allow(dead_code)] // not every enum is read from C today; keep the validator uniformly
            pub(crate) fn from_c(raw: i32) -> Option<Self> {
                match raw {
                    $($val => Some(<$ty>::$variant),)+
                    _ => None,
                }
            }
        }
    };
}

try_from_c_enum! {
    AdActionKind {
        Click = 0, DoubleClick = 1, RightClick = 2, TripleClick = 3,
        SetValue = 4, SetFocus = 5, Expand = 6, Collapse = 7,
        Select = 8, Toggle = 9, Check = 10, Uncheck = 11,
        Scroll = 12, ScrollTo = 13, PressKey = 14, KeyDown = 15,
        KeyUp = 16, TypeText = 17, Clear = 18, Hover = 19, Drag = 20,
    }
}

try_from_c_enum! {
    AdDirection {
        Up = 0, Down = 1, Left = 2, Right = 3,
    }
}

try_from_c_enum! {
    AdModifier {
        Cmd = 0, Ctrl = 1, Alt = 2, Shift = 3,
    }
}

try_from_c_enum! {
    AdMouseButton {
        Left = 0, Right = 1, Middle = 2,
    }
}

try_from_c_enum! {
    AdMouseEventKind {
        Move = 0, Down = 1, Up = 2, Click = 3,
    }
}

try_from_c_enum! {
    AdWindowOpKind {
        Resize = 0, Move = 1, Minimize = 2, Maximize = 3, Restore = 4,
    }
}

try_from_c_enum! {
    AdScreenshotKind {
        Screen = 0, Window = 1, FullScreen = 2,
    }
}

try_from_c_enum! {
    AdImageFormat {
        Png = 0, Jpg = 1,
    }
}

try_from_c_enum! {
    AdSnapshotSurface {
        Window = 0, Focused = 1, Menu = 2, Menubar = 3,
        Sheet = 4, Popover = 5, Alert = 6,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_action_kind_valid_range() {
        for raw in 0..=20 {
            assert!(AdActionKind::from_c(raw).is_some(), "raw = {}", raw);
        }
    }

    #[test]
    fn test_action_kind_out_of_range() {
        assert!(AdActionKind::from_c(-1).is_none());
        assert!(AdActionKind::from_c(21).is_none());
        assert!(AdActionKind::from_c(999).is_none());
        assert!(AdActionKind::from_c(i32::MAX).is_none());
        assert!(AdActionKind::from_c(i32::MIN).is_none());
    }

    #[test]
    fn test_direction_valid_range() {
        for raw in 0..=3 {
            assert!(AdDirection::from_c(raw).is_some());
        }
        assert!(AdDirection::from_c(4).is_none());
    }

    #[test]
    fn test_modifier_valid_range() {
        for raw in 0..=3 {
            assert!(AdModifier::from_c(raw).is_some());
        }
        assert!(AdModifier::from_c(-5).is_none());
    }

    #[test]
    fn test_mouse_button_valid_range() {
        assert!(AdMouseButton::from_c(0).is_some());
        assert!(AdMouseButton::from_c(2).is_some());
        assert!(AdMouseButton::from_c(3).is_none());
    }

    #[test]
    fn test_mouse_event_kind_valid_range() {
        assert!(AdMouseEventKind::from_c(0).is_some());
        assert!(AdMouseEventKind::from_c(3).is_some());
        assert!(AdMouseEventKind::from_c(4).is_none());
    }

    #[test]
    fn test_window_op_kind_valid_range() {
        assert!(AdWindowOpKind::from_c(0).is_some());
        assert!(AdWindowOpKind::from_c(4).is_some());
        assert!(AdWindowOpKind::from_c(5).is_none());
    }

    #[test]
    fn test_screenshot_kind_valid_range() {
        assert!(AdScreenshotKind::from_c(0).is_some());
        assert!(AdScreenshotKind::from_c(2).is_some());
        assert!(AdScreenshotKind::from_c(3).is_none());
    }

    #[test]
    fn test_image_format_valid_range() {
        assert!(AdImageFormat::from_c(0).is_some());
        assert!(AdImageFormat::from_c(1).is_some());
        assert!(AdImageFormat::from_c(2).is_none());
    }

    #[test]
    fn test_enum_raw_round_trip() {
        let k = AdActionKind::Scroll;
        let raw = enum_raw_i32(&k);
        assert_eq!(raw, 12);
        let back = AdActionKind::from_c(raw).unwrap();
        assert!(matches!(back, AdActionKind::Scroll));
    }

    #[test]
    fn test_fuzz_no_panic() {
        // Any raw i32, even crafted bit patterns, must never panic.
        for raw in [-1_000_000_i32, -1, 0, 1, 20, 21, 999, i32::MAX, i32::MIN] {
            let _ = AdActionKind::from_c(raw);
            let _ = AdDirection::from_c(raw);
            let _ = AdModifier::from_c(raw);
            let _ = AdMouseButton::from_c(raw);
            let _ = AdMouseEventKind::from_c(raw);
            let _ = AdWindowOpKind::from_c(raw);
            let _ = AdScreenshotKind::from_c(raw);
            let _ = AdImageFormat::from_c(raw);
        }
    }
}
